Standards:
  -
    Title: Git
    Description: Git
    UID: 0bcc70105ad279503e31fe7b3f47b665
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint
        UID: e064436d3b4dbe9aba8fc00715c46152
        Path: /units/00-Git/00-Git.checkpoint.md
        Autoscore: false
        MaxCheckpointSubmissions: 1
  -
    Title: Java
    Description: Java
    UID: d52387880e1ea22817a72d3759213819
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint
        UID: 9a64c81a9e08c5a99076398595a8675b
        Path: /units/01-Java/01-Java.checkpoint.md
        Autoscore: false
        MaxCheckpointSubmissions: 1
  -
    Title: Javascript
    Description: Javascript
    UID: 9e13b69d1d2da927102acaaaf7154a37
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Checkpoint
        UID: a0f548f7f8d546db0b9f00a9667bdb46
        Path: /units/03-Javascript/03-JavaScript.checkpoint.md
        Autoscore: false
        MaxCheckpointSubmissions: 1
